# Generated by Django 4.0.4 on 2022-05-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_question_correct_answer_alter_quiz_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizitem',
            name='correct_answer',
            field=models.CharField(default='choice a', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizitem',
            name='user_answer',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
