# Generated by Django 4.0.4 on 2022-05-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quizitem_correct_answer_alter_quizitem_user_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizitem',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='quiz',
            name='correct_answers',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='quizitem',
            name='quiz_related_number',
            field=models.SmallIntegerField(default=1),
        ),
    ]
