# Generated by Django 4.0.4 on 2022-05-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_quizitem_correct_answer_quiz_correct_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('a', 'choice a'), ('b', 'choice b'), ('c', 'choice c'), ('d', 'choice d')], max_length=1),
        ),
        migrations.AlterField(
            model_name='quizitem',
            name='user_answer',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
