# Generated by Django 4.0.4 on 2022-05-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='user_quiz_number',
            field=models.IntegerField(default=1),
        ),
    ]
